### ISSUE TITLE
Build error after a few successful build without changing any build settings

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/ember-cordova#181] opened 2016-10-22 11:13 UTC
Hello ember-cordova
i am having this error after a few successive build , whether or not application code is modified.

When i do 
`ember cdv:build --platform=android  --environment=production && ember cdv run`
Repeatedly 

```
ERROR ember-cordova with cordova raw 
Error: /home/v3ss/workspace/ondr.co/chat.ondr.co/client/ember-cordova/cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/v3ss/android-sdk-linux/build-tools/24.0.0/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by v3ss0n** [comment] 2016-10-22 11:14
It was all ok bore , and out of the blue build error occours

**Comment by utilityboy** [comment] 2016-10-22 17:34
This is a duplicate of #164 .

The current workaround is to delete:
 - `ember-cordova/cordova/platforms`
 - `ember-cordova/cordova/plugins`
 - `ember-cordova/cordova/www/plugins`

Then: `ember cdv:prepare`.

Then build as you wish.

**Comment by v3ss0n** [comment] 2016-10-22 19:11
Thanks @utilityboy , this script working very well for me. 
```
rm -rf ember-cordova/cordova/platforms ember-cordova/cordova/plugins ember-cordova/cordova/www/plugins
ember cdv:prepare
ember cdv:build --platform=android --environment=production && ember cdv ru
```

**Comment by alexblom** [comment] 2016-11-05 23:27
Thanka. I'm going to close this and now I'm back from vacation am making progress on that issue. I know what the cause is and just need to figure out how we will resolve it permanently :)

**Closed by alexblom** 2016-11-05 23:27 UTC

**Comment by Ramblurr** [comment] 2017-03-23 12:00
@alexblom  Was this ever fixed? Experiencing it again here.

**Comment by alexblom** [comment] 2017-03-23 21:22
The cases I was aware of should be fixed, but you may see similar issues with failed plugins. The unfortunate solution is to rm plugins/platforms and re-run prepare - but if you have a stable replication case, please re-open or create.
