### ISSUE TITLE
Error installing android platform

### ISSUE THREAD

**Issue by utilityboy** [isleofcode/ember-cordova#86] opened 2016-07-26 18:02 UTC
Hi. Encountering this issue when installing `android` on a newly inited Ember 2.6 repo.

```
ember cdv platform add android
Running 'cordova platform add android'
Adding android project...
Error: Error validating package name. Package name must look like: com.company.Name
File: /bin/sh
Command failed: cordova platform add android
Error: Command failed: cordova platform add android
    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at CoreObject.BashTask.runCommand (/projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:28:16)
    at /projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:22:12
    at lib$rsvp$$internal$$initializePromise (/projects/embercordova/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1084:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/projects/embercordova/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:546:53)
    at new PromiseExt (/projects/embercordova/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at CoreObject.Task.extend.run (/projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:16:12)
    at CoreObject.module.exports.run (/projects/embercordova/node_modules/ember-cordova/lib/commands/cordova.js:60:8)
    at CoreObject.module.exports.validateAndRun (/projects/embercordova/node_modules/ember-cordova/lib/commands/cordova.js:45:17)
```

**Comment by alexblom** [comment] 2016-07-26 18:03
I'm going to close this as it will be a duplicate of #85

**Closed by alexblom** 2016-07-26 18:03 UTC
