### ISSUE TITLE
Cannot open android app after build

### ISSUE THREAD

**Issue by wayne-o** [isleofcode/ember-cordova#198] opened 2016-11-23 18:14 UTC
```
Waynes-MacBook-Pro:sonatribe-ui waynedouglas$ ember cordova:open --platform=android
Opening android project with the default application
The file /Users/waynedouglas/gitlab/sonatribe-ui/cordova/platforms/android/.project does not exist.

Error thrown while running shell command: "open /Users/waynedouglas/gitlab/sonatribe-ui/cordova/platforms/android/.project"
Error: Command failed: /bin/sh -c open /Users/waynedouglas/gitlab/sonatribe-ui/cordova/platforms/android/.project
The file /Users/waynedouglas/gitlab/sonatribe-ui/cordova/platforms/android/.project does not exist.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)Waynes-MacBook-Pro:sonatribe-ui waynedouglas$
```

**Comment by alexblom** [comment] 2016-11-23 18:17
Thanks. This is a duplicate of #171 . For now if you need to run the app, just pop open your Android Studio/Eclipse/IDE manually, or you can also flash with ember cdv run --device.

**Closed by alexblom** 2016-11-23 18:17 UTC
